theme: jekyll-theme-minimal
title: Octave Türkçe Dokümantasyon
description: >-
  GNU Octave kullanımı üzerine Türkçe eğitim notları ve örnekler.
repository: hakankilicaslan/Octave_TR_Doc
repository: kullaniciadi/Octave_TR_Doc