
name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: jeffreytse/jekyll-deploy-action@v0.2.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: '' 
          branch: 'gh-pages' 
          jekyll_src: './'
          jekyll_build_options: ''
          cname: ''
